version: '3.3'
services:
  flask-app:
    build: ./
    image: "flask-app:latest"
    hostname: flask-app
    container_name: flask-app
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./app:/app"
